jobs:
  deploy:
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.16.1
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          path: "**/node_modules"
      - run: npm ci
      - run: npm i vercel -g
      - id: deployment-action
        uses: chrnorm/deployment-action@releases/v1
        with:
          environment: Preview
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: vercel
        run: vercel -b GITHUB_REPOSITORY=$GITHUB_REPOSITORY -b GITHUB_SHA=$GITHUB_SHA -t $VERCEL_TOKEN > environment-url
      - if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ steps.deployment-action.outputs.deployment_id }}
          state: failure
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: environment-url
        run: echo "::set-output name=body::$(cat environment-url)"
      - uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ steps.deployment-action.outputs.deployment_id }}
          environment_url: ${{ steps.environment-url.outputs.body }}
          state: success
          token: ${{ secrets.GITHUB_TOKEN }}

name: Deploy to Preview

on:
  push:
    branches:
      - develop
